variables:
  system.debug: true
jobs:
#   - job: Windows
#     pool:
#       name: Hosted VS2017
#       demands: npm
#     steps:
#       - task: NodeTool@0
#         displayName: 'Use Node 8.x'
#         inputs:
#           versionSpec: 8.x
#       - task: Npm@1
#         displayName: 'Install dependencies'
#         inputs:
#           verbose: false
#       - task: Npm@1
#         displayName: 'Compile sources'
#         inputs:
#           command: custom
#           verbose: false
#           customCommand: 'run compile'
#       - script: 'node node_modules/vscode/bin/test'
#         displayName: 'Run tests'
#       - script: 'npm install -g vsce && vsce package'
#         displayName: 'Build artifact'
#       - task: CopyFiles@2
#         inputs:
#           contents: '*.vsix'
#           TargetFolder: '$(Build.ArtifactStagingDirectory)'
#       - task: PublishBuildArtifacts@1
#         inputs:
#           pathtoPublish: '$(Build.ArtifactStagingDirectory)'
#           artifactName: vs-picgo-dev-build-Windows

  # - job: macOS
  #   pool:
  #     name: Hosted macOS
  #     demands: npm
  #   steps:
  #     - task: NodeTool@0
  #       displayName: 'Use Node 8.x'
  #       inputs:
  #         versionSpec: 8.x
  #     - task: Npm@1
  #       displayName: 'Install dependencies'
  #       inputs:
  #         verbose: false
  #     - task: Npm@1
  #       displayName: 'Compile sources'
  #       inputs:
  #         command: custom
  #         verbose: false
  #         customCommand: 'run compile'
  #     - script: 'node node_modules/vscode/bin/test'
  #       displayName: 'Run tests'
  #     - script: 'npm install -g vsce && vsce package'
  #       displayName: 'Build artifact'
  #     - task: CopyFiles@2
  #       inputs:
  #         contents: '*.vsix'
  #         TargetFolder: '$(Build.ArtifactStagingDirectory)'
  #     - task: PublishBuildArtifacts@1
  #       inputs:
  #         pathtoPublish: '$(Build.ArtifactStagingDirectory)'
  #         artifactName: vs-picgo-dev-build-macOS
  - job: Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false

      - script: 'npm test'
        displayName: 'Complil sources and run tests'
      
      - script: 'node run coveralls'
        displayName: 'Publish code coverage'

      - script: 'npm install -g vsce && vsce package'
        displayName: 'Build artifact'
      - task: CopyFiles@2
        inputs:
          contents: '*.vsix'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: vs-picgo-dev-build
trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
pr:
- dev*